export const PAGE_TITLES: Record<string, string> = {
  "": "Browser\nAutomation for AI",
  installation: "Installation",
  "quick-start": "Quick Start",
  skills: "Skills",
  commands: "Commands",
  configuration: "Configuration",
  plugins: "Plugins",
  selectors: "Selectors",
  snapshots: "Snapshots",
  sessions: "Sessions",
  diffing: "Diffing",
  network: "Network",
  "cdp-mode": "CDP Mode",
  dashboard: "Dashboard",
  streaming: "Streaming",
  recording: "Video Recording",
  debugging: "Debugging",
  profiler: "Profiler",
  react: "React & Web Vitals",
  files: "Files & Clipboard",
  "init-scripts": "Init Scripts",
  proxy: "Proxy",
  ios: "iOS Simulator",
  security: "Security",
  "engines/chrome": "Chrome",
  "engines/lightpanda": "Lightpanda",
  next: "Next.js + Vercel",
  "native-mode": "Native Mode",
  "providers/agentcore": "AgentCore",
  "providers/browser-use": "Browser Use",
  "providers/browserbase": "Browserbase",
  "providers/browserless": "Browserless",
  "providers/kernel": "Kernel",
  changelog: "Changelog",
};

export function getPageTitle(slug: string): string | null {
  return slug in PAGE_TITLES ? PAGE_TITLES[slug]! : null;
}
